# Generated by Django 6.0.3 on 2026-04-12 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vue de page',
                'verbose_name_plural': 'Vues de pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
