# Generated by Django 6.0.3 on 2026-04-12 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse_approx', models.CharField(blank=True, default='', max_length=255)),
                ('type_logement', models.CharField(choices=[('chambre_appart', 'Chambre en appartement'), ('chambre_maison', 'Chambre en maison'), ('appart_partage', 'Appartement partagé'), ('studio_partage', 'Studio partagé')], max_length=20)),
                ('nb_chambres_total', models.PositiveIntegerField()),
                ('nb_chambres_dispo', models.PositiveIntegerField()),
                ('loyer', models.PositiveIntegerField()),
                ('charges_incluses', models.BooleanField(default=False)),
                ('charges_montant', models.PositiveIntegerField(blank=True, null=True)),
                ('equipements', models.JSONField(default=list)),
                ('pref_genre', models.CharField(choices=[('mixte', 'Mixte'), ('femmes', 'Femmes uniquement'), ('hommes', 'Hommes uniquement')], default='mixte', max_length=20)),
                ('pref_fumeur', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20)),
                ('pref_statut', models.CharField(choices=[('etudiant', 'Étudiant'), ('actif', 'Actif'), ('indifferent', 'Indifférent')], default='indifferent', max_length=20)),
                ('date_dispo', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('desactivee', 'Désactivée'), ('coloc_trouvee', 'Coloc trouvée')], default='publiee', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAnnonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_cloudinary', models.URLField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.CharField(choices=[('contenu_inapproprie', 'Contenu inapproprié'), ('arnaque', 'Arnaque suspectée'), ('fausse_annonce', 'Fausse annonce'), ('doublon', 'Annonce en doublon'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_signalant', models.GenericIPAddressField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('decision', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
    ]
