# Generated by Django 6.0.3 on 2026-04-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoannonce',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='annonces.annonce'),
        ),
    ]
